export const testCardsData = [
  {
    id: 1,
    topic: "?",
    title: "Заголовок1",
    date: "10.12.2024",
    status: "Без статуса",
  },
  {
    id: 2,
    topic: "?",
    title: "Заголовок2",
    date: "10.05.2025",
    status: "Без статуса",
  },
  {
    id: 3,
    topic: "?",
    title: "Заголовок3",
    date: "10.11.2025",
    status: "Без статуса",
  },
  {
    id: 4,
    topic: "?",
    title: "Заголовок4",
    date: "15.11.2025",
    status: "Без статуса",
  },
  {
    id: 5,
    topic: "?",
    title: "Заголовок5",
    date: "17.11.2025",
    status: "Без статуса",
  },
  {
    id: 6,
    topic: "?",
    title: "Заголовок6",
    date: "17.11.2025",
    status: "Нужно сделать",
  },
  {
    id: 7,
    topic: "?",
    title: "Заголовок7",
    date: "10.11.2025",
    status: "В работе",
  },
  {
    id: 8,
    topic: "?",
    title: "Заголовок8",
    date: "15.11.2025",
    status: "В работе",
  },
  {
    id: 9,
    topic: "?",
    title: "Заголовок9",
    date: "17.11.2025",
    status: "В работе",
  },
  {
    id: 10,
    topic: "?",
    title: "Заголовок10",
    date: "17.11.2025",
    status: "Тестирование",
  },
  {
    id: 11,
    topic: "?",
    title: "Заголовок11",
    date: "17.11.2025",
    status: "Готово",
  },
  {
    id: 12,
    topic: "?",
    title: "Заголовок12",
    date: "17.11.2025",
    status: "Готово",
  },
];
